#!/usr/bin/env python3
"""No incident-specific literals or machine paths in shipped code.

THE PROBLEM THIS PREVENTS. `verify_owner_report.py` once named a show folder, two
poster md5s and a torrent info hash in its source. That is incident EVIDENCE, not a
check: it cannot see the same fault on another title, it rots when the incident is
gone, and a future session reading the code cannot tell which literals are rules and
which are yesterday's incident. The owner asked the direct question; the answer is a
guard, because "we are careful" is not a mechanism.

WHAT IS LEGITIMATE, AND EXEMPT:
  * comments and DOCSTRINGS may name incidents -- the dense why-comments are the
    codebase's memory. The scan parses with `ast` and looks only at string constants
    that are NOT docstrings, so both a `#` comment and a module/function docstring
    like "TZ held `<tvdbid>325542</tvdbid>`" pass;
  * `scripts/one-off/` and `archive/` are dated repair records by design, and tests
    are fixtures: all three are exempt;
  * launchd labels (`com.mikeyferguson.*`), API endpoints, regexes, extension lists
    and committed DATA tables (`config.COMIC_FRANCHISES`, generated by
    `build_comic_franchises.py`) are identities and rules, not incident constants.

WHAT FAILS: a STRING token in shipped `*.py`/`*.sh` that is a home/machine path
(`/Users/<name>`, `/Volumes/<name>`) or a 32/40-hex digest. Those are the two shapes
the 2026-09-20 incident set used.

    python3 scripts/test_no_incident_hardcoding.py

Read-only. Exit 0 = clean.
"""

from __future__ import annotations

import ast
import io
import re
import subprocess
import sys
import tokenize
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
HOME_PATH = re.compile(r"/(?:Users|Volumes)/[A-Za-z0-9._-]+")
HEX_DIGEST = re.compile(r"\b[0-9a-fA-F]{32}\b|\b[0-9a-fA-F]{40}\b")
EXEMPT = ("/scripts/one-off/", "/archive/", "/test_", "/tests/")

failures: list[str] = []


def check(label, cond):
    print(f"  {'ok  ' if cond else 'FAIL'} {label}")
    if not cond:
        failures.append(label)


def tracked():
    out = subprocess.run(["git", "ls-files", "-z"], cwd=str(REPO),
                         capture_output=True, text=True, check=True).stdout
    for rel in out.split("\0"):
        if not rel or not rel.endswith((".py", ".sh")):
            continue
        if any(x in f"/{rel}" for x in EXEMPT):
            continue
        yield REPO / rel


def _is_docstring(node):
    return isinstance(node.value, ast.Constant) and isinstance(node.value.value, str)


def string_literals(path):
    """String constants that are NOT docstrings -- i.e. strings that can be behaviour."""
    try:
        tree = ast.parse(path.read_text(encoding="utf-8", errors="ignore"))
    except (OSError, SyntaxError):
        return
    docs = set()
    for node in ast.walk(tree):
        if isinstance(node, (ast.Module, ast.ClassDef, ast.FunctionDef,
                             ast.AsyncFunctionDef)):
            body = getattr(node, "body", [])
            if body and isinstance(body[0], ast.Expr) and _is_docstring(body[0]):
                docs.add((body[0].value.lineno, body[0].value.col_offset))
    for node in ast.walk(tree):
        if isinstance(node, ast.Constant) and isinstance(node.value, str):
            if (node.lineno, node.col_offset) not in docs:
                yield node.lineno, node.value


offenders = []
scanned = 0
for path in tracked():
    scanned += 1
    for lineno, text in string_literals(path):
        for rx, what in ((HOME_PATH, "machine path"), (HEX_DIGEST, "digest")):
            m = rx.search(text)
            if m:
                offenders.append(f"{path.relative_to(REPO)}:{lineno}: {what} {m.group(0)[:24]!r}")

print(f"scanned {scanned} shipped source file(s) (comments exempt, one-off/archive/tests exempt)")
check("no machine paths or digests in shipped string literals", not offenders)
for o in offenders[:20]:
    print(f"      {o}")

# BOTH DIRECTIONS: the detector must fire on a synthetic offender and NOT on a
# comment that names the same incident.
synthetic = io.BytesIO(
    b"x = '/Users/someone/Media/Shows/Thing'\n"
    b"h = '05520557851cb23ea38e121ed2713514'\n").readline
synthetic_offenders = 0
for tok in tokenize.tokenize(synthetic):
    if tok.type == tokenize.STRING:
        if HOME_PATH.search(tok.string) or HEX_DIGEST.search(tok.string):
            synthetic_offenders += 1
check("the detector fires on a synthetic offender", synthetic_offenders == 2)

comment_only = io.BytesIO(
    b"# the incident held <tvdbid>325542</tvdbid> and /Users/someone/Media\n"
    b"y = 1\n").readline
comment_strings = [tok.string for tok in tokenize.tokenize(comment_only)
                   if tok.type == tokenize.STRING]
check("a comment naming the incident is not a string literal",
      not any(HOME_PATH.search(s) or HEX_DIGEST.search(s) for s in comment_strings))

print()
if failures:
    print(f"{len(failures)} FAILURE(S)")
    raise SystemExit(1)
print("no incident hard-coding in shipped code")
